<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
      <private>False</private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
      <private>False</private>
    </Reference>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

</Project>
